# Use the official ASP.NET Core image with Windows Server Core
FROM mcr.microsoft.com/dotnet/aspnet:8.0-windowsservercore-ltsc2022 AS base
WORKDIR /app
EXPOSE 80

# Use the SDK image to build the app
FROM mcr.microsoft.com/dotnet/sdk:8.0-windowsservercore-ltsc2022 AS build
WORKDIR /src
COPY ["AksDemoWebsite.csproj", "."]
RUN dotnet restore "AksDemoWebsite.csproj"
COPY . .
WORKDIR "/src"
RUN dotnet build "AksDemoWebsite.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "AksDemoWebsite.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "AksDemoWebsite.dll"]